SHOW DATABASES;
USE PROJECTS;
CREATE TABLE IF NOT EXISTS STUDENTS
(
    NAME VARCHAR(15) NOT NULL PRIMARY KEY,
    AGE INT NOT NULL,
    SEX CHAR(1) NOT NULL,
    MATRIC INT NOT NULL UNIQUE,
    AGGREGATE INT NOT NULL
);

DESC STUDENTS;


